// Generated by AppIcon/make_icons.py from the icon SVGs; run it again instead of editing this file.

import SwiftUI
import UIKit

extension SupporterIcon {
    /// An icon's colors, taken from its artwork: the accent the app's controls take, and the background
    /// wash's back mountain and sun, already at the wash's opacity.
    struct Palette {
        let accent: Color
        let mountain: Color
        let sun: Color

        /// Where the wash's colors sit, from the top: the mountain, the sun, and where it has faded out.
        static let locations: [CGFloat] = [0.0, 0.35, 0.7]
    }

    var palette: Palette {
        switch self {
        case .classic:
            Palette(
                accent: Color(UIColor(red: 0.349, green: 0.431, blue: 0.953, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.349, green: 0.431, blue: 0.953, alpha: 0.16), dark: UIColor(red: 0.184, green: 0.157, blue: 0.788, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.945, green: 0.537, blue: 0.275, alpha: 0.1), dark: UIColor(red: 0.988, green: 0.271, blue: 0.145, alpha: 0.14))
            )
        case .amethyst:
            Palette(
                accent: Color(UIColor(red: 0.592, green: 0.380, blue: 0.788, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.592, green: 0.380, blue: 0.788, alpha: 0.16), dark: UIColor(red: 0.408, green: 0.125, blue: 0.612, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.925, green: 0.537, blue: 0.424, alpha: 0.1), dark: UIColor(red: 0.945, green: 0.318, blue: 0.333, alpha: 0.14))
            )
        case .aurora:
            Palette(
                accent: Color(UIColor(red: 0.000, green: 0.573, blue: 0.545, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.000, green: 0.573, blue: 0.545, alpha: 0.16), dark: UIColor(red: 0.000, green: 0.353, blue: 0.337, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.922, green: 0.494, blue: 0.725, alpha: 0.1), dark: UIColor(red: 0.886, green: 0.286, blue: 0.745, alpha: 0.14))
            )
        case .blush:
            Palette(
                accent: Color(UIColor(red: 0.694, green: 0.380, blue: 0.510, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.694, green: 0.380, blue: 0.510, alpha: 0.16), dark: UIColor(red: 0.502, green: 0.157, blue: 0.318, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.886, green: 0.569, blue: 0.408, alpha: 0.1), dark: UIColor(red: 0.894, green: 0.392, blue: 0.259, alpha: 0.14))
            )
        case .cyberLime:
            Palette(
                accent: Color(UIColor(red: 0.392, green: 0.420, blue: 0.949, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.392, green: 0.420, blue: 0.949, alpha: 0.16), dark: UIColor(red: 0.231, green: 0.133, blue: 0.784, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.541, green: 0.729, blue: 0.302, alpha: 0.1), dark: UIColor(red: 0.349, green: 0.663, blue: 0.000, alpha: 0.14))
            )
        case .dune:
            Palette(
                accent: Color(UIColor(red: 0.682, green: 0.424, blue: 0.267, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.682, green: 0.424, blue: 0.267, alpha: 0.16), dark: UIColor(red: 0.482, green: 0.220, blue: 0.000, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.863, green: 0.592, blue: 0.318, alpha: 0.1), dark: UIColor(red: 0.851, green: 0.443, blue: 0.000, alpha: 0.14))
            )
        case .ember:
            Palette(
                accent: Color(UIColor(red: 0.800, green: 0.314, blue: 0.306, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.800, green: 0.314, blue: 0.306, alpha: 0.16), dark: UIColor(red: 0.584, green: 0.000, blue: 0.094, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.941, green: 0.541, blue: 0.263, alpha: 0.1), dark: UIColor(red: 0.937, green: 0.353, blue: 0.000, alpha: 0.14))
            )
        case .evergreen:
            Palette(
                accent: Color(UIColor(red: 0.000, green: 0.588, blue: 0.396, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.000, green: 0.588, blue: 0.396, alpha: 0.16), dark: UIColor(red: 0.000, green: 0.365, blue: 0.239, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.878, green: 0.588, blue: 0.184, alpha: 0.1), dark: UIColor(red: 0.816, green: 0.471, blue: 0.000, alpha: 0.14))
            )
        case .glacier:
            Palette(
                accent: Color(UIColor(red: 0.000, green: 0.549, blue: 0.682, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.000, green: 0.549, blue: 0.682, alpha: 0.16), dark: UIColor(red: 0.000, green: 0.341, blue: 0.427, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.824, green: 0.722, blue: 0.490, alpha: 0.1), dark: UIColor(red: 0.784, green: 0.612, blue: 0.235, alpha: 0.14))
            )
        case .lagoon:
            Palette(
                accent: Color(UIColor(red: 0.000, green: 0.565, blue: 0.592, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.000, green: 0.565, blue: 0.592, alpha: 0.16), dark: UIColor(red: 0.000, green: 0.349, blue: 0.365, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.937, green: 0.533, blue: 0.404, alpha: 0.1), dark: UIColor(red: 0.953, green: 0.318, blue: 0.247, alpha: 0.14))
            )
        case .matcha:
            Palette(
                accent: Color(UIColor(red: 0.357, green: 0.553, blue: 0.369, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.357, green: 0.553, blue: 0.369, alpha: 0.16), dark: UIColor(red: 0.122, green: 0.361, blue: 0.153, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.761, green: 0.647, blue: 0.302, alpha: 0.1), dark: UIColor(red: 0.702, green: 0.545, blue: 0.000, alpha: 0.14))
            )
        case .midnightGold:
            Palette(
                accent: Color(UIColor(red: 0.220, green: 0.369, blue: 0.557, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.220, green: 0.369, blue: 0.557, alpha: 0.16), dark: UIColor(red: 0.027, green: 0.212, blue: 0.424, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.808, green: 0.624, blue: 0.314, alpha: 0.1), dark: UIColor(red: 0.761, green: 0.510, blue: 0.000, alpha: 0.14))
            )
        case .noir:
            Palette(
                accent: Color(UIColor(red: 0.482, green: 0.498, blue: 0.525, alpha: 1)),
                mountain: .dynamic(light: UIColor(red: 0.482, green: 0.498, blue: 0.525, alpha: 0.16), dark: UIColor(red: 0.286, green: 0.306, blue: 0.337, alpha: 0.3)),
                sun: .dynamic(light: UIColor(red: 0.973, green: 0.502, blue: 0.416, alpha: 0.1), dark: UIColor(red: 1.000, green: 0.247, blue: 0.176, alpha: 0.14))
            )
        }
    }
}

private extension Color {
    static func dynamic(light: UIColor, dark: UIColor) -> Color {
        Color(UIColor { traits in traits.userInterfaceStyle == .dark ? dark : light })
    }
}
